### ISSUE TITLE
Are you accepting contributions?

### ISSUE THREAD

**Issue by ghost** [DarthAffe/CUE.NET#1]
I just plugged in a new K70 RGB keyboard and went searching on GitHub for something like this.

What kinds of things would you like to see in this library? Are you going to stick to just wrapping the SDK, or are convenience methods (say, for lighting effects) allowed?

**Comment by DarthAffe** [comment]
Hey voltagex,
of course I'm going to accept contributions!

I see this library as an "high-level-API" (for programmers) and I just posted on the corsair forum to get some opinions about what would be useful.
I don't want to clone CUE (I don't see any point in this - since it does what it's made for) but I think support for things like effects, "drawing" on the keyboard and so on could be added quite easily, as long as I'm able to bring some structure to the "core"-code :p

**Comment by ghost** [comment]
Cool. The library seems a bit confusing - I created a keyboard object
before realising I needed to use the static version in the SDK namespace.

Also, should there be an examples project?

**Comment by DarthAffe** [comment]
I totally agree, but at the moment I'm not sure what's the best way to go. There has to be some kind of factory to handle all that handshake stuff, but it's quite bad right now.
Well there's quite a lot to do until it's "production ready" :p

I'm currently writing a simple example project to reflect the current development state.

**Comment by ghost** [comment]
I'm happy to help any way I can. Probably best to put this kind of discussion into a TODO or similar instead of this issue
