### ISSUE TITLE
CUESDK.x64_2013.dll Doesn't Work?

### ISSUE THREAD

**Issue by Dresden11** [DarthAffe/CUE.NET#29]
CUESDK.x64_2013.dll cannot be referenced, make sure it is a valid assembly, or COM file.

**Comment by DarthAffe** [comment]
"CUESDK.x64_2013.dll" can't be referenced, since it's the native CUE-SDK and not a C#-assembly. You just have to reference the CUE.NET.dll and place/deploy the CUESDK.x64_2013.dll inside you application folder.

I would highly recommend you to use the latest NuGet-Package and not the release version! It's easier to install, works for both x86 and x64 and is by far more advanced and stable.

**Comment by Dresden11** [comment]
Thanks, will try it now.
