### ISSUE TITLE
Would I be able to change profiles within the corsair utility engine?

### ISSUE THREAD

**Issue by loganintech** [DarthAffe/CUE.NET#33]
For example, 

```
if(someValue)
{
    SetProfile(myCustomCUEProfile);
}
```

**Comment by DarthAffe** [comment]
No, currently the CUE-SDK only allows to set LED-colors.
It might be possible if there are undocumented api possibilities or of course through a memory-hack, but I haven't investigated both so far.
I can investigate it this weekend, but I haven't much hope to find a solution which doesn't trigger any av :p: 

PS: Would it be of some use if it would be possible to load exported CUE-profile-settings? 'Depending on the format this might be implemented without too much effort.

**Comment by loganintech** [comment]
I think that would be a useful feature, however many profiles are often very complicated and can contain lighting effects that respond to key presses. I have not delved fully into your api implementation of effects but it would be a highly interesting feature for those who want to just make the color schemes in CUE and manipulate them in a C# application.

**Comment by DarthAffe** [comment]
> lighting effects that respond to key presses.

Ah i forgot about that ...
Well I'll dig a bit into that now - maybe I'm able to find some kind of workaround.

And to be honest I'm absolutely not happy with the effect thing until now (that's why it isn't even documented) but I'm not sure how to implement it better ...

**Comment by DarthAffe** [comment]
I'm sorry but I don't see a possibility to implement profile-switching with the current abilities of the SDK.
I found two promising things while looking around:
1. 3 named pipes provided by CUE - but since they are not documented It's hard to find functions which aren't yet in the sdk (if there are even any).
2. The profile-switcher from corsair-forums - this seems to be the only working approach but since it depends on restarting cue to reload configurations it's impossible to use with the SDK (it's closing the connection and leave you unable to do anything)

The only way I can image to get a solution close to that, is to load the profiles (or at least the colors without effects, assignments etc.) and switch between them.
I'll implement a simple loading mechanism for profiles now :)

**Comment by DarthAffe** [comment]
I just created a new release containing the new possibility to load simple profile-data.
I'm sorry but this is all I'm able to do right now. If the SDK will ever allow to do something or someone gets a solution I'll of course implement it :)
