### ISSUE TITLE
On application publish, x64 and x86 folders are not included by default

### ISSUE THREAD

**Issue by loganintech** [DarthAffe/CUE.NET#37]
Specifically when generating a one click installer but I assume the same for others too.

**Comment by DarthAffe** [comment]
I haven't used the publish feature myself so far but until now it seems that only files added to the project are copied while publishing. The x64/x86 folders are copied by an build-target that's why they aren't included here.
I'm not sure if it's possible to add do something similar for the publishing task, but I'll need some time to understand how what that publish-stuff works.

**Comment by loganintech** [comment]
Ok no problems thanks a bunch. We're using CUE for https://github.com/SpoinkyNL/Artemis. You should check it out :)

**Comment by DarthAffe** [comment]
It should work with [this](https://github.com/DarthAffe/CUE.NET/commit/7a0a2778babde37232b81953f24fcc68eb84a948) change.
If you're using the latest nuget-package just update, if you are on the stable one you can workaround it until I create a new version (I won't only for this change) by replacing the file _<solution folder>/packages/CUE.NET.<version>/build/net45/CUE.NET.targets_ with the changed one from the commit.

(Please drop me a short message here if it works for you or not.)

**Comment by RobertBeekman** [comment]
Hey, could you compile this fix please? :)

Nuget package is still 1.0.2

**Comment by DarthAffe** [comment]
done (it might take a few minutes until the new package is listed)

**Comment by RobertBeekman** [comment]
Thank you!

I can also confirm it's properly including it now within the publish :+1:
