### ISSUE TITLE
Question: How to use FlashEffect?

### ISSUE THREAD

**Issue by hanshammel1337** [DarthAffe/CUE.NET#41]
hello,

how do i use the FlashEffect correct?

`FlashEffect testeffect = new FlashEffect(Color.Blue);`
`testeffect.Repetitions = 100;`
`keyboard.AttachEffect(testeffect);`
`keyboard.Update();`

the keyboard light up all leds with blue, but just one time. there is no flash effect.
how do i handle the effect update correctly?

btw: thx, for this nice work!

**Comment by DarthAffe** [comment]
Well first of all: sorry for the missing of documentation for effects.
This code is perfectly fine, all you're missing is to set a 'background' for the keyboard. Since the keyboard itself is transparent by default it can't go back to anything after fading to blue.

Just add the background (for example solid black):

``` C#
keyboard.Brush = new SolidColorBrush(Color.Black);
FlashEffect testeffect = new FlashEffect(Color.Blue);
keyboard.AttachEffect(testeffect);
```

Note that you don't need to set the repetition count if you want it to last forever (which might be the case if set to 100 - i don't know what you are planning :p).

You also don't need to update the keyboard as long as an effect is attached. (This of course isn't the case if you changed the default UpdateMode. [documentation](https://github.com/DarthAffe/CUE.NET/wiki/Perform-basic-lighting#manualautomatic-update) (note that it lacks the fact that the default value is 'AutoOnEffect' which keeps updating [like Continuous, as long as the effect is active])

**Comment by DarthAffe** [comment]
Just one more note:
The flash effect has quite a big amount of parameters. If you take [this](http://cue.wyrez.org/class_c_u_e_1_1_n_e_t_1_1_effects_1_1_flash_effect.html#properties) as reference the default values are wrong (I don't know why but it seems like they are always one property to low. The default value for repetitions (that's missing because of that) is 0.

The ones in the descriptions are correct.

**Comment by hanshammel1337** [comment]
Thanks for your fast and helpful answer. With a set keyboard brush everthing is fine now. The standard values for the parameters are good for my project. But I will look in the documantion later for some fine-tuning :-)
Can be closed (at least it was never an real 'issue' ;)
