### ISSUE TITLE
Error 404 

### ISSUE THREAD

**Issue by Nachh** [DarthAffe/CUE.NET#42]
Hi first of all i am a beginner!

 I am getting 404 error trying installing from nuget package manager, i have tried with myget feed and nuget repository. In the other hand i cant install manually cause i know how to add dll's as reference but i dont know how to create a post-built event.

Thx !

**Comment by DarthAffe** [comment]
Hmm, since nuget.org is preconfigured in visual studio it should always work, myget can be a bit tricky but at the moment there is no difference between the packages.

Are you sitting behind a proxy which isn't configured correctly to work with visual studio? This could be the reason for a 404.
If this isn't the case you could try the de-select restart select method someone is advicing [here](http://stackoverflow.com/a/14897606).
