### ISSUE TITLE
Reinitialize interrupts any executing macro

### ISSUE THREAD

**Issue by LordJZ** [DarthAffe/CUE.NET#44]
If there's a macro running while Initialize/Reinitialize is called, then the macro will be interrupted. Ran into this issue when trying to [workaround](https://github.com/LordJZ/MicStatus/commit/37b9159d4aedc91eaa06b0aea8b2c7d8f8b72624) losing CUE connection on wake up.

Corsair ticket 6778416, it might be their issue.

**Comment by DarthAffe** [comment]
I'm 100% sure, that this problem is CUE-related.
I could reproduce the behavior you described with CUE but not with the CUE 2 Beta I'm using right now.
So this problem seems to be already fixed but will take some time until it's available.

I did the following:
1. I created a macro in CUE recording me pressing the digits from 1 to 7 with 2 seconds delay.
2. I started the macro and ran a test-application containing this code

``` C#
CueSDK.Initialize();

CorsairKeyboard keyboard = CueSDK.KeyboardSDK;
if (keyboard == null)
     throw new WrapperException("No keyboard found");

keyboard.Brush = new SolidColorBrush(Color.Black);
keyboard.Update();
Wait(3);

keyboard.Brush = new SolidColorBrush(Color.Yellow);
keyboard.Update();
Wait(3);

CueSDK.Reinitialize();
Wait(3);

keyboard.Brush = new SolidColorBrush(Color.Green);
keyboard.Update();
Wait(3);

return;
```
1. In CUE 1 the macro stopped at the reinitialize leaving the output 12345, in CUE 2 I got the full output 1234567 and the lighting was as expected.

**Comment by LordJZ** [comment]
@DarthAffe could you please point me out how can I get CUE 2? Thanks.

**Comment by DarthAffe** [comment]
As you can read [here](http://forum.corsair.com/v3/showthread.php?t=158759) the beta entry is currently closed. I'm afraid that you'd have to wait until it's officially released.

**Comment by LordJZ** [comment]
OK, thanks for looking into this!
