### ISSUE TITLE
Corsair Wireless VOID issue (CUE2)

### ISSUE THREAD

**Issue by RobertBeekman** [DarthAffe/CUE.NET#47]
Hello,

I'm having some trouble with the VOID on CUE2. I'm not sure whether it's related to CUE.NET or the native SDK. 

The headset doesn't apply the colors it simply turns the LEDs off. When it does apply colors (seemingly at random) it's at a very slow rate

I did some debugging and it turns out it's a combination of not taking exclusive access and updating something else besides the headset.

I made a Gist showing the issue: https://gist.github.com/SpoinkyNL/6a7903f0a61f1c2d5ec24df1e25ac855

If you think it's not a CUE.NET issue I'll make a post on the CUE2 beta forum

**Comment by DarthAffe** [comment]
Have you tried to reproduce this with the color-pulse-example from the SDK? This is the easiest way to see if it's CUE related or a problem in CUE.NET.

**Comment by RobertBeekman** [comment]
Just gave it a go, works alright there

**Comment by DarthAffe** [comment]
Well since I can't reproduce this error (no headset :p) and the code itself looks fine I've to ask you to try some more things:
1. Is this Problem only for Headsets? Or are mice affected to if updated first?
2. Does the update-order affect this problem? (Does updating headsets last fix it?
3. Could you add some debug-output to the test and check if the headset-keys are really initialized?

I'm, pretty sure that CUE2 does something different on handling updates - the color-pulse-example updates all keys at once, CUE.NET runs selective updates on each device - this might cause the issue, but it is no excuse^^

**Comment by RobertBeekman** [comment]
Huh, I changed it to update the headset last and that made a difference, it now colors it somewhat, but gets into a fight with CUE2 over what color to give it.

You don't actually need a headset to try it out, if you go into CUE2 and uncheck "Show only connected devices"

http://i.imgur.com/coC6cKk.png

You can see the VOID demo, the LED there matches what is shown in real life
http://i.imgur.com/lEHV5at.png

**Comment by DarthAffe** [comment]
Well, I really hope that this is a bug. The headset is resetting back to the configured lighting effect (static green in my test) every time a key-update without the headset keys is done. I don't see any reason why this would be a expected behaviour but if its, it would require an ugly workaround.
Could you report this to the corsair-guys? If they say it's not a bug I'll fix it but I'd rather like to get the behaviour of CUE 1 here.

**Comment by RobertBeekman** [comment]
I posted it on the CUE2 beta forums but didn't get a reply. While looking at some other VOID issues I came across a beta firmware. Issue seems to be resolved with that, although it still feels a bit laggier than in 1.x.

In any case not a CUE.NET issue :)
