### ISSUE TITLE
Uninitialize or Shutdown functionality

### ISSUE THREAD

**Issue by antonpup** [DarthAffe/CUE.NET#48]
Hello, I am wondering if it would be possible to include a Shutdown function, in the event where the app does not need CUE SDK lighting, to allow CUE itself to take over with lighting profiles. And then at a later point reinitialize again, if CUE SDK lighting is needed.

Because at the moment, you can only `CueSDK.Initialize();` and `CueSDK.Reinitialize();`

**Comment by DarthAffe** [comment]
As long as you don't request exclusive access (Initialize(true)) `CueSDK.Reinitialize();` will hand all light's back to CUE.
You are right that this won't prevent CUE.NET from interfere with CUE-lighting if you call update afterwards (or don't set the update-mode to manual before reinitializing). But this is something you have to take care of.

Using `CueSDK.Reinitialize();` as an uninitialize-function might be counter-intuitive at first, but even if I'd add a method which really unloads the whole SDK you'd have to stop updating the keyboard (otherwise it would crash). So right now I don't see any reason to do this.

**Comment by antonpup** [comment]
I do use exclusive mode. Which is why I would like to release the lighting back to CUE. If not an exclusive shutdown function, can you allow for exclusive mode to reinitialize as non-exclusive i.e. `CueSDK.Initialize(true); CueSDK.Reinitialize(false);`

**Comment by DarthAffe** [comment]
This is possible, just call `CueSDK.Reinitialize(false);` and `CueSDK.Reinitialize(true);` if you want to get exclusive access back

**Comment by antonpup** [comment]
Thank you. That seems to have done it.
